name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # recommended: every 6 hours
  workflow_dispatch:      # manual trigger
  push:
    branches:
      - main              # change to 'master' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write     # ensure workflow has read/write permissions to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animations
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show generated files
        run: |
          ls dist

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
